GET http://localhost:3000/api/hello

###
POST http://localhost:3000/api/chats
Content-Type: application/json

{
  "message": "Olá"
}

###
GET http://localhost:3000/api/chats


@chatId = 37ee68cb-2c93-4ac8-843a-ce0fbbf30fcc

###
GET http://localhost:3000/api/chats/{{chatId}}/messages

###
POST  http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json

{
  "message": "Olá"
}

###
@messageId = 43290d26-51dc-445d-8931-63f597bc97da

GET http://localhost:3000/api/messages/{{messageId}}/events