GET http://localhost:3000/api/hello

###
POST http://localhost:3000/api/chats
Content-Type: application/json

{
  "message": "Hello"
}

###
GET http://localhost:3000/api/chats


@chatId = cb8e42f7-7684-423c-8055-2bfe265bb78d

###
GET http://localhost:3000/api/chats/{{chatId}}/messages

###
POST  http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json

{
  "message": "ola"
}

###
@messageId = 43290d26-51dc-445d-8931-63f597bc97da

GET http://localhost:3000/api/messages/{{messageId}}/events